
server:
  port: 9092
  http2:
    enabled: true

logging:
  level:
    org.springframework.web: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: keycloak_client
            client-secret: N3drwZNV9t0QtAVKFhnuvR7hFEYngqyY
            scope: openid, profile
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: http://localhost:8084/realms/keycloak_realm
            user-name-attribute: preferred_username
  keycloak:
    server-url: http://localhost:8084/realms/keycloak_realm
    realm: keycloak_realm
    username: admin
    password: admin